package org.eclipse.milo.opcua.sdk.server.services2;

import org.eclipse.milo.opcua.stack.core.types.builtin.ExpandedNodeId;
import org.jetbrains.annotations.Nullable;

public enum Service {

    DISCOVERY_FIND_SERVERS,
    DISCOVERY_FIND_SERVERS_ON_NETWORK,
    DISCOVERY_GET_ENDPOINTS,
    DISCOVERY_REGISTER_SERVER,
    DISCOVERY_REGISTER_SERVER_2,

    SECURE_CHANNEL_OPEN_SECURE_CHANNEL,
    SECURE_CHANNEL_CLOSE_SECURE_CHANNEL,

    SESSION_CREATE_SESSION,
    SESSION_ACTIVATE_SESSION,
    SESSION_CLOSE_SESSION,
    SESSION_CANCEL,

    NODE_MANAGEMENT_ADD_NODES,
    NODE_MANAGEMENT_ADD_REFERENCES,
    NODE_MANAGEMENT_DELETE_NODES,
    NODE_MANAGEMENT_DELETE_REFERENCES,

    VIEW_BROWSE,
    VIEW_BROWSE_NEXT,
    VIEW_BROWSE_TRANSLATE_BROWSE_PATHS,
    VIEW_BROWSE_REGISTER_NODES,
    VIEW_BROWSE_UNREGISTER_NODES,

    QUERY_QUERY_FIRST,
    QUERY_QUERY_NEXT,

    ATTRIBUTE_READ,
    ATTRIBUTE_HISTORY_READ,
    ATTRIBUTE_WRITE,
    ATTRIBUTE_HISTORY_UPDATE,

    METHOD_CALL,

    MONITORED_ITEM_CREATE_MONITORED_ITEMS,
    MONITORED_ITEM_MODIFY_MONITORED_ITEMS,
    MONITORED_ITEM_SET_MONITORING_MODE,
    MONITORED_ITEM_SET_TRIGGERING,
    MONITORED_ITEM_DELETE_MONITORED_ITEMS,

    SUBSCRIPTION_CREATE_SUBSCRIPTION,
    SUBSCRIPTION_MODIFY_SUBSCRIPTION,
    SUBSCRIPTION_SET_PUBLISHING_MODE,
    SUBSCRIPTION_PUBLISH,
    SUBSCRIPTION_REPUBLISH,
    SUBSCRIPTION_TRANSFER_SUBSCRIPTIONS,
    SUBSCRIPTION_DELETE_SUBSCRIPTIONS;


    public static @Nullable Service

    from(ExpandedNodeId typeId) {
        return null; // TODO
    }

}
